[package]
authors = ["Logan Buckley <logan.buckley@gmail.com>"]
name = "logos"
version = "0.1.0"

[dependencies]
cdrs = "1.0.0-rc.2"
clap = "2.24.2"
combine = "2.3.2"
itertools = "0.6.0"
lazy_static = "0.2.8"
prettytable-rs = "0.6.6"
r2d2 = "0.7.2"
rmp-serde = "0.13.3"
rusqlite = "0.12.0"
rustyline = "1.0.0"
serde = "1.0.8"
serde_derive = "1.0.8"
zmq = "0.8.1"

[dependencies.chrono]
features = ["serde"]
version = "0.3.1"

[dependencies.uuid]
features = ["v4"]
version = "0.5.0"
