[package]
authors = ["Logan Buckley <logan.buckley@gmail.com>"]
name = "logos"
version = "0.1.0"

[dependencies]
bytes = "0.4"
r2d2 = "0.7.2"
clap = "2.24.2"
serde = "1.0.8"
futures = "0.1"
tokio-io = "0.1"
combine = "2.3.2"
tokio-core = "0.1"
itertools = "0.6.0"
lru-cache = "0.1.1"
rusqlite = "0.12.0"
rustyline = "1.0.0"
cdrs = "1.0.0-rc.2"
tokio-proto = "0.1"
rmp-serde = "0.13.3"
lazy_static = "0.2.8"
tokio-service = "0.1"
serde_derive = "1.0.8"
prettytable-rs = "0.6.6"

[dependencies.zmq]
version = "0.8.1"
default-features = false

[dependencies.chrono]
features = ["serde"]
version = "0.3.1"

[dependencies.uuid]
features = ["v4"]
version = "0.5.0"
